// Design specimen, not a statement of Ocean's commercial performance.
const {OceanDeck}=require('../../lib/ocean');
(async()=>{
 const d=new OceanDeck({title:'Ocean RCS publication system',draft:true,confidential:false});
 d.cover({title:'One clear story.\nEvery page considered.',subtitle:'Ocean RCS / Renewable Connected Systems',date:'Publication system / 2026'});
 d.divider({number:1,title:'Clarity starts with structure',subtitle:'A shared visual language for presentations, proposals and reports.'});
 d.statement({eyebrow:'Editorial standard',headline:'The evidence leads the page',support:'Make the important information easy to find. Use scale, spacing and a clear hierarchy to guide the reader.'});
 d.twoColumn({eyebrow:'Choose the right format',headline:'A presentation and a report serve different reading needs',left:{label:'Presentation',points:['One idea per slide','A concise narrative for a meeting','Editable charts and supporting appendix']},right:{label:'Proposal or report',points:['Enough detail to make a decision','Flowing text with clear scope and evidence','Readable pages designed for PDF delivery']}});
 d.pillars({eyebrow:'Shared design language',headline:'A consistent system with room for the content',pillars:[{title:'Typography',text:'Stack Sans Headline sets the hierarchy. Font size follows the reading format.'},{title:'Color',text:'White creates space. Blackmoss carries the message. Sage adds restrained emphasis.'},{title:'Evidence',text:'Tables, charts and real photographs explain something specific.'}]});
 d.metrics({eyebrow:'Type scale',headline:'Scale gives the reader a clear entry point',metrics:[{value:'48',label:'Cover title',note:'Points / presentation'},{value:'32',label:'Page headline',note:'Points / presentation'},{value:'17',label:'Body copy',note:'Points / presentation'},{value:'11',label:'Report prose',note:'Points / Letter document'}],footnote:'Design specifications only. These values are not business metrics.'});
 d.timeline({eyebrow:'Production',headline:'A repeatable path from brief to final PDF',phases:[{label:'01 / Brief',title:'Define the decision',text:'Identify the audience and the evidence needed.'},{label:'02 / Compose',title:'Build the narrative',text:'Select layouts that fit the content.'},{label:'03 / Verify',title:'Inspect every page',text:'Check fonts, fit, evidence and visual balance.'},{label:'04 / Deliver',title:'Share the final',text:'Provide a verified PDF and editable source.'}]});
 d.table({eyebrow:'Color roles',headline:'The same palette, used with more restraint',header:['Role','Color','Primary use'],colW:[3.0,3.0,6.133],rows:[['Canvas','White','Open backgrounds and light covers'],['Primary ink','Blackmoss','Headlines, prose and numbers'],['Accent','Sage','Large emphasis and restrained rules'],['Secondary ink','Cedar','Small labels and supporting copy'],['Structure','Peacock','Table headers and chart series']]});
 d.chart({eyebrow:'Editable evidence',headline:'Charts explain a comparison without decoration',categories:['A','B','C','D'],series:[{name:'Illustrative series',values:[2,4,3,5]}],takeaway:'Use direct units and a visible source. Keep the key comparison easy to read.',footnote:'ILLUSTRATIVE DESIGN DATA ONLY. Not a forecast or Ocean performance claim.'});
 d.caseStudy({eyebrow:'Project evidence',headline:'A case study begins with verified facts',facts:[{label:'Identity',value:'Name the actual project'},{label:'Scope',value:'State the delivered work'},{label:'Status',value:'Distinguish planned and completed'},{label:'Source',value:'Link the supporting record'}],summary:'Add a real project photograph when available. Never create a synthetic site to imply execution.'});
 d.team({eyebrow:'Company overview',headline:'Credibility comes from specific responsibilities',people:[{name:'Leadership',role:'COMMERCIAL RESPONSIBILITY',bio:'Use a verified name, role and concise record of relevant experience.'},{name:'Operations',role:'DELIVERY RESPONSIBILITY',bio:'Explain the work this person owns. Avoid inflated descriptions.'},{name:'Technical',role:'TECHNICAL RESPONSIBILITY',bio:'Include confirmed qualifications. Use a supplied headshot or no photo.'}]});
 d.ask({eyebrow:'Next action',headline:'Close with the decision and its supporting steps',amount:'[TBD]',amountLabel:'Verified project amount',uses:[{label:'Approved scope',value:'[TBD]'},{label:'Terms',value:'[TBD]'}],nextSteps:['Review the evidence','Resolve open assumptions','Confirm the agreed next action'],notes:'Draft layout placeholder. Release mode blocks unresolved values.'});
 d.appendix({title:'Keep useful detail accessible',header:['Record','Include','Purpose'],colW:[3,5.5,3.633],rows:[['Source register','Document, date and owner','Trace each important claim'],['Assumptions','Input, basis and limitation','Show what remains uncertain'],['Technical detail','Relevant scope and specifications','Support diligence'],['Commercial terms','Verified inclusions and exclusions','Make boundaries explicit']]});
 await d.save('ocean-layout-reference');
})().catch(e=>{console.error(e);process.exit(1)});
