// Design specimen content, not a statement of Ocean's commercial performance. Figures are illustrative;
// photographs are AI-generated representative images. One content file feeds every recipe length.
const path = require('path');
const IMG = f => path.join(__dirname, '../../assets/images', f);
module.exports = {
  deck: {title: 'Ocean RCS layout reference', draft: true, classification: 'confidential', status: 'specimen', kind: 'Layout reference', client: 'Ocean RCS'},
  sections: [
    {name: 'Site', title: 'Clarity starts with the site', subtitle: 'Roof, structure, service and the constraints that shape the array.'},
    {name: 'System', title: 'A system built for the building', subtitle: 'Solar, storage and interconnection sized to the load.'},
    {name: 'Economics', title: 'The numbers that decide it', subtitle: 'Savings, incentives and payback on verified inputs.'},
    {name: 'Next steps', title: 'Decisions and schedule', subtitle: 'What we need from you and when.'},
  ],
  slides: {
    cover: {layout: 'cover', kicker: 'Commercial energy', title: 'Rooftop Solar\n+ Storage', date: 'Layout reference',
      subtitle: 'Client name', meta: [['Date', '26 Sep 2026'], ['Status', 'Specimen']]},
    agenda: {layout: 'agenda', items: [{key: 'Site', title: 'What the roof and service can carry'}, {key: 'System', title: 'Solar, storage and interconnection'},
      {key: 'Economics', title: 'Savings, incentives and payback'}, {key: 'Next steps', title: 'Decisions and schedule'}]},
    situation: {layout: 'statement', section: 'Site', eyebrow: 'Site', headline: 'The roof is ready and\nthe service has room',
      support: 'A new TPO roof, clear array zones and an existing 2,000 A service mean the site can carry **about 412 kW** without a service upgrade.',
      bottomLine: 'No service upgrade needed for the first phase.'},
    site: {layout: 'caseStudy', section: 'Site', eyebrow: 'Site', headline: 'The roof can carry about\n412 kW of solar', lede: 'A new TPO roof, clear array zones and an existing 2,000 A service.',
      image: IMG('rooftop.jpg'), imageLabel: 'Representative image', summary: 'Representative image of a comparable rooftop array.',
      facts: [{label: 'Array size', value: '412 KW DC'}, {label: 'Usable roof', value: '68,400 FT²'}, {label: 'Service', value: '2,000 A · 480 V'}]},
    siteData: {layout: 'metrics', section: 'Site', eyebrow: 'Site', headline: 'Four figures define\nthe opportunity', lede: 'Illustrative figures for the specimen.',
      metrics: [{value: '412 kW', label: 'Array size', note: 'After keep-outs'}, {value: '1.2 MWh', label: 'Storage', note: 'Two cabinets'},
        {value: '2,000 A', label: 'Service', note: 'To be confirmed'}, {value: '6.4 yrs', label: 'Payback', note: 'After incentives', highlight: true}],
      bottomLine: 'Payback in 6.4 years with the existing service.', footnote: 'Illustrative figures · specimen'},
    solution: {layout: 'caseStudy', section: 'System', eyebrow: 'System', headline: 'Solar and storage sized\nto the building', lede: 'One array, two cabinets, one interconnection.',
      image: IMG('bess.jpg'), imageLabel: 'Representative image', summary: 'Representative image of a comparable storage installation.',
      facts: [{label: 'Solar', value: '412 KW DC'}, {label: 'Storage', value: '1.2 MWH'}, {label: 'Interconnection', value: 'Line-side tap'}]},
    systemPhoto: {layout: 'statement', section: 'System', eyebrow: 'System', headline: 'Built and verified\nby our own crews', image: IMG('worker.jpg'),
      support: 'Every cabinet is **tested, torqued and logged** before handover. ==One team== owns the work from design to commissioning.'},
    systemDetail: {layout: 'pillars', section: 'System', eyebrow: 'System', headline: 'Three parts, one\nintegrated system', lede: 'Each part is engineered to the site.',
      pillars: [{title: 'Solar array', text: '412 kW DC on the new TPO roof, laid out around keep-outs and access paths.'},
        {title: 'Battery storage', text: 'Two 600 kWh cabinets shave peaks and carry critical loads.'},
        {title: 'Interconnection', text: 'A line-side tap on the existing 2,000 A service, subject to utility approval.'}]},
    schedule: {layout: 'timeline', section: 'System', eyebrow: 'System', headline: 'A repeatable path from\nbrief to handover',
      phases: [{label: '01 · Brief', title: 'Define the decision', text: 'Identify the audience and the evidence needed.'},
        {label: '02 · Design', title: 'Build the system', text: 'Engineer the array, storage and service.'},
        {label: '03 · Verify', title: 'Commission on site', text: 'Test, torque and log every cabinet.'},
        {label: '04 · Deliver', title: 'Hand over', text: 'Provide records, training and support.'}]},
    econChart: {layout: 'chart', section: 'Economics', eyebrow: 'Economics', headline: 'Savings grow each year\nas utility rates rise', lede: 'Annual bill savings, years 1–10, $K. Year 10 highlighted.',
      categories: ['Y01', 'Y02', 'Y03', 'Y04', 'Y05', 'Y06', 'Y07', 'Y08', 'Y09', 'Y10'],
      series: [{name: 'Annual savings', values: [62, 66, 70, 75, 79, 84, 88, 93, 98, 104]}],
      takeaway: 'Savings rise from $62K to $104K a year.', bottomLine: '10-year savings of $819K. Payback in 6.4 years.'},
    econTable: {layout: 'table', section: 'Economics', eyebrow: 'Economics', headline: 'System summary and\nopen items',
      header: ['Item', 'Specification', 'Status'], colW: [3.4, 5.2, 3.533],
      rows: [['Solar array', '412 kW DC', 'Confirmed layout'], ['Battery storage', '1.2 MWh', 'Pending utility'], ['Interconnection', '2,000 A line-side tap', 'Application due'], ['Roof', 'New TPO, 20-year warranty', 'Complete']],
      footnote: 'Illustrative figures · specimen'},
    key: {layout: 'keyNumber', kicker: 'Economics', value: '38%', text: 'Lower grid electricity spend from the first year',
      meta: [['Basis', '12-month interval data'], ['Status', 'Illustrative']]},
    nextSteps: {layout: 'ask', section: 'Next steps', eyebrow: 'Next steps', headline: 'Close with the decision\nand its next steps', amount: '[TBD]', amountLabel: 'Verified project amount',
      uses: [{label: 'Approved scope', value: '[TBD]'}, {label: 'Terms', value: '[TBD]'}],
      nextSteps: ['Review the evidence', 'Resolve open assumptions', 'Confirm the agreed next action'],
      notes: 'Draft layout placeholder. Release mode blocks unresolved values.'},
    close: {layout: 'back'},
  },
};
