// Source: Ocean_RCS_Confidential_Internal_Diligence_Appendix_Redesigned.pdf, supplied 27 Sep 2026.
// Diligence standards only; nothing here establishes completed diligence or an acquired asset.
const path = require('path');
const PHOTO = path.join(__dirname, '../../investor/mobility-energy-platform/images/solar-carport-campus.jpg');
module.exports = {
  deck: {title: 'Ocean RCS Confidential Internal Diligence Appendix', draft: true,
    classification: 'internal', status: 'draft', footer: 'Ocean RCS · Confidential', kind: 'Diligence appendix', client: 'Ocean RCS'},
  sections: [{name: 'Assets'}, {name: 'Sites'}, {name: 'Controls'}, {name: 'Review'}],
  slides: {
    cover: {layout: 'cover', kicker: 'Confidential internal appendix', title: 'Diligence\nAppendix',
      date: 'Renewable Connected Systems', meta: [['Date', '27 Sep 2026'], ['Status', 'Draft']],
      notes: 'Source pages 1 and 8. Internal support for diligence, not a public-facing platform thesis. Ocean RCS is the market-facing brand. Project legal entities may be formed at acquisition, property closing, financing or operations launch. Preliminary information is subject to diligence.'},
    agenda: {layout: 'agenda', items: [{key: 'Assets', title: 'Equipment sourcing and evidence'},
      {key: 'Sites', title: 'Incentives and underwriting'}, {key: 'Controls', title: 'Risk owners and capital gates'},
      {key: 'Review', title: 'Evidence before capital release'}]},
    site: {layout: 'table', section: 'Assets', eyebrow: 'Equipment', headline: 'Equipment sourcing\nrequires diligence',
      lede: 'DCFC, BESS and infrastructure inventory remain subject to transaction review.',
      header: ['Review area', 'Required evidence'], colW: [3.6, 8.533],
      rows: [['Serials / title', 'Model, title chain, location, custody and serial records'],
        ['Condition', 'Inspection, photos, missing parts and commissioning path'],
        ['Warranty / support', 'OEM status, serviceability and parts access'],
        ['Comparable value', 'Documented public references and invoices'],
        ['Deployment / protection', 'Named site or redeployment plan; collateral, escrow and insurance']],
      notes: 'Source pages 2-3. Specific equipment transactions remain internal unless used for a transaction-specific investor meeting. Core investor materials should not depend on a single inventory transaction.'},
    siteData: {layout: 'statement', section: 'Assets', eyebrow: 'Deployment', headline: 'Project demand\ngoverns equipment fit',
      support: 'Title, condition and serviceability must support a named deployment or redeployment plan.',
      image: PHOTO, imageFocus: [0.35, 0.55], imageLabel: 'Ocean project photo: DJI_0482',
      notes: 'Source pages 2-3. User confirmed the photo is a real Ocean project. It illustrates the project setting; it is not evidence of charger inventory, equipment ownership or completed diligence.'},
    systemPhoto: {layout: 'table', section: 'Sites', eyebrow: 'Incentives', headline: 'Incentives require\nwritten confirmation',
      lede: 'Eligibility, reservation status and documentation precede capital planning.',
      header: ['Program layer', 'Confirmation required'], colW: [3.6, 8.533],
      rows: [['Federal', 'Tax-credit eligibility, domestic content and energy-community review'],
        ['State / utility', 'Make-ready, EVSE, storage, solar or managed-charging programs'],
        ['Local', 'Permits, grants, economic development or site programs'],
        ['Capital planning', 'Award or reservation confirmed before net-capital adjustment']],
      notes: 'Source page 4. A screening checklist, not a claim of eligibility, incentive value or award. Current program rules require transaction-specific professional verification.'},
    systemDetail: {layout: 'caseStudy', section: 'Sites', eyebrow: 'Underwriting', headline: 'Site underwriting\nconnects the evidence',
      lede: 'Physical feasibility, commercial demand and operating readiness must align.',
      image: PHOTO, imageFocus: [0.65, 0.5], imageLabel: 'Ocean project photo',
      summary: 'Ocean project photo: DJI_0482; no site findings inferred',
      facts: [{label: 'Site', value: 'Access, flood, setbacks, parking'},
        {label: 'Power', value: 'Load, utility path, tariff, switchgear'},
        {label: 'Demand', value: 'Charging, fleet, tenant or compute'},
        {label: 'Scope', value: 'Civil, electrical, equipment, timing'}],
      notes: 'Source page 5. Physical review also includes site layout. Operating-model evidence includes monitoring, O&M, billing and service plans. This photo does not establish any specific site finding.'},
    econChart: {layout: 'table', section: 'Controls', eyebrow: 'Risk controls', headline: 'Each risk has an owner\nand a go/no-go threshold',
      header: ['Risk category', 'Control standard'], colW: [3.6, 8.533],
      rows: [['Utility / interconnection', 'Written feasibility and cost path'], ['Permits / zoning', 'Documented approval path'],
        ['Equipment', 'Title, inspection and serviceability'], ['Demand', 'Contract, LOI or site-specific model'],
        ['Construction', 'Scope, budget, schedule and lien controls']],
      notes: 'Source pages 5-6. Every risk needs an owner, diligence evidence and a go/no-go threshold. Operating evidence must include monitoring, O&M, billing and service planning.'},
    key: {layout: 'keyNumber', kicker: 'Capital controls', value: '5', text: 'funding gates require documented evidence',
      meta: [['Basis', 'Diligence process'], ['Status', 'Draft']],
      notes: 'Source page 7. Five gates: Control, Validate, Fund, Build, Operate. This count describes the appendix process, not assets or commitments.'},
    nextSteps: {layout: 'timeline', section: 'Review', eyebrow: 'Funding gates', headline: 'Capital release\nfollows evidence',
      phases: [{label: '01 · Control', title: 'Rights', text: 'LOI, option, customer agreement or development right.'},
        {label: '02 · Validate', title: 'Diligence', text: 'Utility, permits, incentives, title and technical review.'},
        {label: '03 · Fund', title: 'Approval', text: 'Investor approval, lender commitment or customer-funded EPC.'},
        {label: '04 · Build', title: 'Draw controls', text: 'Commissioning and construction oversight.'},
        {label: '05 · Operate', title: 'Reporting', text: 'Performance data, billing and O&M.'}],
      footnote: 'Internal diligence only. Preliminary information remains subject to review.',
      notes: 'Source pages 7-8. Project-specific legal entities may be formed at acquisition, property closing, financing or operations launch. Multiple lanes may advance before asset-level funding.'},
    close: {layout: 'back'}
  }
};
